### ISSUE TITLE
Prepend baseurl when linking assets

### ISSUE THREAD

**Issue by digitalcraftsman** [dim0627/hugo_theme_solit#1]
Hello @dim0627,

currently, the demo of your theme on the theme site would break. The reason is that you theme assumes assets like backgrounds at `example.com/images/...`. However, the theme site puts each theme in a seperate sub-directory.

Therefore, you theme (including the assets you want to link) end up at `example.com/theme/hugo_theme_solit/...`. By prepending the base url you can avoid that problem.

**Comment by dim0627** [comment]
Hello @digitalcraftsman ,

I'm sorry, It was the lack of my consideration.
And I fixed this probrem.
I'm sorry, please check again.

Regards,
Daisuke Tsuji

**Comment by digitalcraftsman** [comment]
Looks good.
