### ISSUE TITLE
error running template on a fresh hugo installation

### ISSUE THREAD

**Issue by andreabisello** [dim0627/hugo_theme_solit#2]
Hi, thanks for your template.

running hugo server on ubuntu machine without any modification i obtain

andrea@andrea-HP-G61-Notebook-PC:~/Documenti/hardwaretips$ hugo server
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/_default/baseof.html:18: function "replaceRE" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/_default/li.html:1: function "md5" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/_default/li_sm.html:1: function "md5" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/_default/summary.html:1: function "md5" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/partials/single_json_ld.html:12: function "default" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/partials/single_meta.html:4: function "default" not defined
ERROR: 2016/10/07 17:35:52 template.go:350: template: theme/shortcodes/img.html:2: function "default" not defined

andrea@andrea-HP-G61-Notebook-PC:~/Documenti/hardwaretips$ hugo version
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T18:14:17+01:00

how to solve this issue?

thanks.

**Comment by dim0627** [comment]
Hi

What your hugo version?

2016/10/08 0:52 "Andrea Bisello" notifications@github.com:

**Comment by andreabisello** [comment]
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T18:14:17+01:00

**Comment by andreabisello** [comment]
i installed by apt-get install hugo

**Comment by dim0627** [comment]
Ok, thanks
I investigating now, sorry wait a minute please.

2016/10/08 1:00 "Andrea Bisello" notifications@github.com:

**Comment by dim0627** [comment]
Sorry, I can't reproduced it.
Please tell me golang version.

My investigate environment is,

Hugo Static Site Generator v0.16 BuildDate: 2016-10-08T01:59:02+09:00

go version go1.6.2 darwin/amd64

2016-10-08 1:13 GMT+09:00 Daisuke Tsuji dim0627@gmail.com:

**Comment by andreabisello** [comment]
i have no go installed.

is golang required?

i'm installing by apt-get install golang-go

**Comment by andreabisello** [comment]
andrea@andrea-HP-G61-Notebook-PC:~/Documenti/hardwaretips$ go version
go version go1.6.2 linux/amd64

never changed.

i downloaded again the theme and i tried with a fresh website, but nothing changed.

thanks anyway

**Comment by dim0627** [comment]
hmm, OK.
I'm sorry, I have no idea.
I'll try on Ubuntu.

**Comment by dim0627** [comment]
> Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T18:14:17+01:00

OK, I think this version of Hugo is not implements `replaceRE`, `md5`
Can you upgrade to v0.16 from v0.16-DEV the Hugo version?

**Comment by andreabisello** [comment]
sorry for the delay.
yes, the problem is the version of hugo.
i installed downloading the .deb from github and installing by dpkg -i and the problem is solved.

thanks and sorry for the mistake.

**Comment by dim0627** [comment]
Awesome😄 !
