### ISSUE TITLE
Strange look of Cyrillic (Russian) font

### ISSUE THREAD

**Issue by paskal** [dim0627/hugo_theme_solit#7]
Hello!

$subj, when I'm building my [blog](https://github.com/paskal/terrty/tree/master/blog) source for Cyrillic font I see the picture which drastically different from the Latin characters render:

![image](https://user-images.githubusercontent.com/712534/37678498-4de36f3c-2c8f-11e8-9ae1-c9ad5e963d35.png)

**Comment by dim0627** [comment]
https://github.com/dim0627/hugo_theme_solit#configtoml-example

This theme supported changing base fonts your own.
Please try change to another font 😄
