### ISSUE TITLE
Solit Theme Demo is broken on the Hugo Themes Website

### ISSUE THREAD

**Issue by onedrawingperday** [dim0627/hugo_theme_solit#9]
Hi @dim0627 

The issue is identical to what I already posted in https://github.com/dim0627/hugo_theme_aglaus/issues/17 

You need to replace all instances of `.Source` with `.File` for your theme's demo to be generated again.

Please do this and let me know.

Thanks.

CC / @digitalcraftsman

**Comment by dim0627** [comment]
Thanks for your information 👍 
I'm so sorry, I could not maintain this theme because I not using Hugo now.
`Hide Old Themes #430` is good proposal, you can hide my themes on Theme registry.

Regards
